### PR TITLE
update label field for better autocompleting experience

### PR DESCRIPTION
**Pull request by xylonx**
change label field in the gitmoji config with setting label field layout as `${emoji} ${description}` for better
searching and autocompleting

### CODE REVIEW

**Comment by xylonx** [comment]
@bendera Feel soory for not seeing pr #36 ever. I have added a field named `description_zh_CN` in scripts/gitmojis.json in commit adeb375b282d451646529dfa480aa799e589b651. If you feel it is not proper, I'll remove that commit.

**Comment by bendera** [comment]
I would keep the original structure of the `gitmoji.json` file because it will facilitate the future updates. That file copied from the [gitmoji repo](https://github.com/carloscuesta/gitmoji/blob/master/src/data/gitmojis.json). Furthermore I would like to keep the old configs, so please create new configs with different filenames, for example: gitmojis_searchable-description.json, gitmojis_searchable-description_zh-CN.json. After the merging I will create a readme file in the `example-configs` directory to describe the content of the files.

**Comment by xylonx** [comment]
Thanks for your explain. I would like to do what you said and change my pr commit as soon as possible. Again, apologize for my rude change to `gitmoji.json`

**Comment by bendera** [comment]
No problem, and thanks for your contribution. :)

**Comment by xylonx** [comment]
I have updated my pr commits. I add a new config file named 'gitmojis_searchable.json' for example gitmojis config generation. In addition, I have done a little change: update the field layout as `${emoji}(${name}) ${description}` for remaining compatibility of searching by name.

**Pull request closed without merging**
